data:
  name: mnist
  batch_size: 128
  num_workers: 4

model:
  hidden_channels: 64
  num_blocks: 8

training:
  epochs: 50
  lr: 0.001
  weight_decay: 0.0
  save_path: "./checkpoints/"
